name: 'Setup Aliyun Serverless-Devs'
description: 'An Action for Setup Aliyun Serverless-Devs'
author: 'heimanba'
branding:
  icon: 'heart'
  color: 'red'

inputs:
  account_id: 
    description: 'Aliyun Main Account ID'
    required: true
  access_key_id: 
    description: 'Aliyun Access Key ID'
    required: true
  access_key_secret: 
    description: 'Aliyun Access Key Secret'
    required: true
  access:
    description: 'Access Alias Name'
    required: true
    default: 'default'

runs:
  using: "composite"
  steps:
    - run: ./script.sh ${{ inputs.account_id }} ${{ access_key_id }} ${{ access_key_secret }} ${{ access }}
      shell: bash